USE socialdb;

CREATE TABLE IF NOT EXISTS publications(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(300) NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    author_id INT NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=INNODB;
